// src/components/svelte/Pane.svelte
<script lang="ts">
    import { createEventDispatcher, onMount, onDestroy } from "svelte";
    import { flattenDepartures, getActiveAlerts } from "../data/transitUtils";
    import type { NearbyDeparturesFromCoordsV2Response } from "../types/birchtypes";
    import type { DisplayItem } from "../types/DisplayItem";
    import type { PaneConfig } from "../types/PaneConfig"; // Ensure this matches usage

    export let config: PaneConfig;
    export let isEditing = false;
    export let style = "";
    export let className = "";
    export let theme = "default";
    export let use24h = true;
    export let deviceLocation: { lat: number; lon: number } | null = null;
    export let clickableTrips = false;

    const dispatch = createEventDispatcher();

    function handleTripClick(item: DisplayItem) {
        if (!clickableTrips) return;

        // Construct the URL for the Enroute Display
        // Assuming we need trip ID and chateau
        if (item.tripId && item.chateau) {
            window.location.href = `/?mode=enroute&trip=${item.tripId}&chateau=${item.chateau}&24h=${use24h}&theme=${theme}`;
        }
    }

    // Local Data State
    let nearbyData: NearbyDeparturesFromCoordsV2Response | null = null;
    let loading = true;
    let error: string | null = null;
    let minuteTick = 0;

    // Derived State
    $: effectiveLocation = config.location || deviceLocation;
    $: radius = config.radius || 1500;

    // Fetching Logic
    let dataInterval: NodeJS.Timeout;

    // Initial fetch and interval
    $: {
        if (effectiveLocation) {
            fetchData();
            if (dataInterval) clearInterval(dataInterval);
            dataInterval = setInterval(fetchData, 30000);
        } else {
            loading = false;
            error = "No location configured";
        }
    }

    function fetchData() {
        if (!effectiveLocation) return;
        loading = true;

        // Use effectiveLocation
        const url = `https://birch.catenarymaps.org/nearbydeparturesfromcoordsv2?lat=${effectiveLocation.lat}&lon=${effectiveLocation.lon}&radius=${radius}`;

        fetch(url)
            .then((res) => {
                if (!res.ok)
                    throw new Error(`HTTP error! status: ${res.status}`);
                return res.json();
            })
            .then((data) => {
                nearbyData = data;
                loading = false;
                error = null;
            })
            .catch((err: any) => {
                console.error(err);
                error = err.message; // localized error
                loading = false;
            });
    }

    // Minute tick for updating relative times
    onMount(() => {
        const tickTimer = setInterval(() => minuteTick++, 30000);
        return () => clearInterval(tickTimer);
    });

    onDestroy(() => {
        if (dataInterval) clearInterval(dataInterval);
    });

    // Compute display items
    $: allDepartures = flattenDepartures(nearbyData, use24h, minuteTick);
    $: activeAlerts = getActiveAlerts(nearbyData);

    import {
        getDisplayItemsFiltered,
        groupDepartures,
        type RouteGroup,
    } from "../../utils/PaneLogic";

    $: displayItems = getDisplayItemsFiltered(allDepartures, config);

    function handleEdit(e: Event) {
        e.stopPropagation();
        dispatch("edit");
    }

    $: groupedItems =
        config.displayMode === "grouped_by_route"
            ? groupDepartures(displayItems)
            : [];

    $: gapStyle =
        config.simpleListGap !== undefined
            ? `gap: ${parseFloat(config.simpleListGap) * 0.25}rem`
            : "gap: 0.5rem";

    $: paddingStyle =
        config.simplePaddingX !== undefined &&
        config.simplePaddingY !== undefined
            ? `padding: ${parseFloat(config.simplePaddingY) * 0.25}rem ${parseFloat(config.simplePaddingX) * 0.25}rem`
            : config.useRouteColor
              ? "padding: 0.25rem 0.5rem"
              : "padding: 0";
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<div
    class={`relative overflow-hidden rounded-lg border border-slate-600 flex flex-col ${className} ${theme === "default" ? "bg-slate-800/50" : ""}`}
    {style}
>
    <!-- Header / Config Bar -->
    <div
        class={`flex items-center justify-between px-3 py-1 border-b border-slate-600 ${isEditing ? "border-yellow-500/50" : ""} ${theme === "default" ? "bg-slate-900/80" : ""}`}
    >
        <span class="font-bold text-sm text-slate-300 truncate">
            {config.name ||
                (config.type === "departures" ? "Departures" : "Alerts")}
        </span>
        {#if isEditing}
            <button
                on:click={handleEdit}
                class="text-[10px] uppercase font-bold bg-yellow-600 text-black px-2 py-0.5 rounded ml-2 hover:bg-yellow-500"
            >
                Edit
            </button>
        {/if}
    </div>

    <!-- Content -->
    <div class="flex-grow overflow-auto p-2 scrollbar-hide">
        {#if loading && !nearbyData}
            <div class="flex items-center justify-center h-full">
                <span class="text-white/50 text-xs animate-pulse"
                    >Loading data...</span
                >
            </div>
        {:else if error}
            <div
                class="flex items-center justify-center h-full p-4 text-center"
            >
                <span class="text-red-400 text-xs">{error}</span>
            </div>
        {:else if config.type === "departures"}
            <div class="flex flex-col" style={gapStyle}>
                {#if displayItems.length > 0}
                    {#if config.displayMode === "train_departure"}
                        <!-- Train Departure Mode -->
                        <!-- Train Departure Mode -->
                        <div class="overflow-x-auto">
                            <table
                                class="w-full text-left font-mono text-sm border-spacing-0"
                            >
                                <thead>
                                    <tr
                                        class="text-xs font-bold text-slate-400 border-b border-slate-700"
                                    >
                                        {#if config.showRouteShortName !== false}
                                            <th class="px-2 py-1">Rte</th>
                                        {/if}
                                        <th class="px-2 py-1">Time</th>
                                        {#if config.showTripShortName !== false}
                                            <th class="px-2 py-1">Trip</th>
                                        {/if}
                                        <th class="px-2 py-1 w-full"
                                            >Direction</th
                                        >
                                        <th class="px-2 py-1 text-right"
                                            >Plat</th
                                        >
                                    </tr>
                                </thead>
                                <tbody>
                                    {#each displayItems as item (item.key)}
                                        <tr
                                            class="items-center {config.useRouteColor
                                                ? 'text-white font-bold'
                                                : 'border-b border-slate-700 last:border-0'} {clickableTrips
                                                ? 'cursor-pointer hover:bg-white/10'
                                                : ''}"
                                            style={config.useRouteColor
                                                ? `background-color: ${item.color}; color: ${item.textColor}`
                                                : ""}
                                            on:click={() =>
                                                handleTripClick(item)}
                                        >
                                            {#if config.showRouteShortName !== false}
                                                <td class="px-2 py-1 font-bold">
                                                    {item.routeShortName}
                                                </td>
                                            {/if}
                                            <td
                                                class="px-2 py-1 whitespace-nowrap"
                                            >
                                                {item.formattedTime}
                                            </td>
                                            {#if config.showTripShortName !== false}
                                                <td class="px-2 py-1 font-bold">
                                                    {item.tripShortName}
                                                </td>
                                            {/if}
                                            <td
                                                class="px-2 py-1 truncate max-w-[100px]"
                                            >
                                                {item.headsign}
                                            </td>
                                            <td class="px-2 py-1 text-right">
                                                {item.platform || "-"}
                                            </td>
                                        </tr>
                                    {/each}
                                </tbody>
                            </table>
                        </div>
                    {:else if config.displayMode === "grouped_by_route"}
                        <!-- Grouped by Route Mode (Unified Layout) -->
                        <div class="flex flex-col gap-2">
                            {#each groupedItems as group}
                                <!-- svelte-ignore a11y-click-events-have-key-events -->
                                <div
                                    class="flex rounded overflow-hidden border border-slate-600 bg-slate-800/50"
                                >
                                    <!-- Route Badge (Left Sidebar) -->
                                    <div
                                        class="w-12 flex items-center justify-center font-bold text-2xl shrink-0 p-2 border-r border-slate-700"
                                        style={config.groupingTheme === "ratp"
                                            ? `background-color: ${group.routeColor}; color: ${group.routeTextColor}`
                                            : "background-color: rgba(30, 41, 59, 0.5);"}
                                    >
                                        {#if config.groupingTheme === "ratp"}
                                            <!-- RATP Style: Circular Badge -->
                                            <div
                                                class="w-8 h-8 rounded-full border-2 border-current flex items-center justify-center"
                                            >
                                                {group.routeShortName.replace(
                                                    " Line",
                                                    "",
                                                )}
                                            </div>
                                        {:else}
                                            <!-- Standard Style: Simple Text -->
                                            <span
                                                class="text-white"
                                                style="color: {group.routeColor}"
                                                >{group.routeShortName.replace(
                                                    " Line",
                                                    "",
                                                )}</span
                                            >
                                        {/if}
                                    </div>

                                    <!-- Directions (Right Content) -->
                                    <div
                                        class="flex flex-col flex-grow text-xs"
                                    >
                                        {#each group.directions as direction, idx}
                                            <div
                                                class="flex items-center justify-between p-2 gap-2 {idx <
                                                group.directions.length - 1
                                                    ? 'border-b border-slate-700'
                                                    : ''} {idx % 2 === 0
                                                    ? 'bg-white/5'
                                                    : ''}"
                                            >
                                                <!-- Direction Name -->
                                                <div
                                                    class="font-bold truncate text-sm flex-grow"
                                                >
                                                    {direction.headsign}
                                                </div>

                                                <!-- Times -->
                                                <div
                                                    class="flex items-center gap-2 shrink-0"
                                                >
                                                    {#each direction.items as item}
                                                        <!-- svelte-ignore a11y-click-events-have-key-events -->
                                                        <div
                                                            class={config.groupingTheme ===
                                                            "ratp"
                                                                ? "bg-black/40 rounded px-1.5 py-0.5 min-w-[3rem] text-center"
                                                                : ""}
                                                            role="button"
                                                            tabindex="0"
                                                            on:click|stopPropagation={() =>
                                                                handleTripClick(
                                                                    item,
                                                                )}
                                                            class:cursor-pointer={clickableTrips}
                                                            class:hover:opacity-80={clickableTrips}
                                                        >
                                                            <span
                                                                class="font-bold text-lg leading-none"
                                                                class:text-yellow-500={config.groupingTheme ===
                                                                    "ratp"}
                                                                class:text-white={config.groupingTheme !==
                                                                    "ratp"}
                                                            >
                                                                {item.min}
                                                            </span>
                                                            <span
                                                                class="text-[9px] opacity-70 ml-0.2 leading-none"
                                                                >min</span
                                                            >
                                                        </div>
                                                    {/each}
                                                </div>
                                            </div>
                                        {/each}
                                    </div>
                                </div>
                            {/each}
                        </div>
                    {:else}
                        <!-- Simple (Default) Mode -->
                        {#each displayItems as item (item.key)}
                            <!-- svelte-ignore a11y-click-events-have-key-events -->
                            <div
                                class="rounded leading-none flex items-center justify-between shadow hover:brightness-110 shrink-0 {clickableTrips
                                    ? 'cursor-pointer'
                                    : 'cursor-default'}"
                                style={(config.useRouteColor
                                    ? `background-color: ${item.color}; color: ${item.textColor}; `
                                    : "") + paddingStyle}
                                role="button"
                                tabindex="0"
                                on:click={() => handleTripClick(item)}
                            >
                                <div class="flex-grow overflow-hidden mr-2">
                                    <div
                                        class="flex items-baseline gap-1 overflow-hidden"
                                    >
                                        <span
                                            class="font-bold whitespace-nowrap"
                                            >{item.routeShortName}</span
                                        >
                                        <span class="font-medium truncate"
                                            >to {item.headsign}</span
                                        >
                                    </div>
                                </div>
                                <div
                                    class="font-bold text-lg whitespace-nowrap"
                                >
                                    {item.min}<span
                                        class="text-xs font-light ml-0.5"
                                        >min</span
                                    >
                                </div>
                            </div>
                        {/each}
                    {/if}
                {:else}
                    <div class="text-white/50 text-center text-sm py-4">
                        No departures found.
                    </div>
                {/if}
            </div>
        {:else}
            <!-- Alerts View -->
            <div class="flex flex-col gap-2">
                {#if activeAlerts.length > 0}
                    {#each activeAlerts as alert, idx}
                        <div
                            class="bg-yellow-900/40 border border-yellow-700/50 p-2 rounded text-sm text-yellow-100"
                        >
                            {alert}
                        </div>
                    {/each}
                {:else}
                    <div class="text-white/50 text-center text-sm py-4">
                        No active alerts.
                    </div>
                {/if}
            </div>
        {/if}
    </div>

    <!-- Overlay -->
    {#if isEditing}
        <!-- svelte-ignore a11y-click-events-have-key-events -->
        <div
            on:click={handleEdit}
            class="absolute inset-0 bg-black/10 hover:bg-black/20 cursor-pointer transition-colors z-10 flex items-center justify-center opacity-0 hover:opacity-100"
            role="button"
            tabindex="0"
        >
            <span
                class="bg-black/80 text-white px-3 py-1 rounded-full text-xs font-bold pointer-events-none"
                >Configure Pane</span
            >
        </div>
    {/if}
</div>

// src/components/Pane.tsx
import React, { useEffect, useMemo, useState } from "react";
import { flattenDepartures, getActiveAlerts } from "./data/transitUtils";
import {
    getDisplayItemsFiltered,
    groupDepartures,
    type RouteGroup,
} from "../utils/PaneLogic";
import type { NearbyDeparturesFromCoordsV2Response } from "./types/birchtypes";
import type { DisplayItem } from "./types/DisplayItem";
import type { PaneConfig } from "./types/PaneConfig";

interface PaneProps {
    config: PaneConfig;
    isEditing?: boolean;
    style?: React.CSSProperties;
    className?: string;
    theme?: string;
    use24h?: boolean;
    deviceLocation?: { lat: number; lon: number } | null;
    clickableTrips?: boolean;
    onEdit?: () => void;
}

export const Pane: React.FC<PaneProps> = ({
    config,
    isEditing = false,
    style,
    className = "",
    theme = "default",
    use24h = true,
    deviceLocation = null,
    clickableTrips = false,
    onEdit,
}) => {
    // Derived Configuration
    const effectiveLocation = config.location || deviceLocation;
    const radius = config.radius || 1500;

    // State
    const [nearbyData, setNearbyData] = useState<NearbyDeparturesFromCoordsV2Response | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [minuteTick, setMinuteTick] = useState(0);

    // Fetch Logic
    useEffect(() => {
        let mounted = true;
        let intervalId: NodeJS.Timeout;

        const fetchData = async () => {
            if (!effectiveLocation) {
                if (mounted) {
                    setLoading(false);
                    setError("No location configured");
                }
                return;
            }

            if (mounted) setLoading(true);

            const url = `https://birch.catenarymaps.org/nearbydeparturesfromcoordsv2?lat=${effectiveLocation.lat}&lon=${effectiveLocation.lon}&radius=${radius}`;

            try {
                const res = await fetch(url);
                if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
                const data = await res.json();
                if (mounted) {
                    setNearbyData(data);
                    setLoading(false);
                    setError(null);
                }
            } catch (err: any) {
                console.error(err);
                if (mounted) {
                    setError(err.message);
                    setLoading(false);
                }
            }
        };

        if (effectiveLocation) {
            fetchData();
            intervalId = setInterval(fetchData, 30000);
        } else {
            setLoading(false);
            setError("No location configured");
        }

        return () => {
            mounted = false;
            if (intervalId) clearInterval(intervalId);
        };
    }, [
        // Using stringified effectiveLocation to avoid deep dependency issues if object ref changes
        effectiveLocation ? `${effectiveLocation.lat},${effectiveLocation.lon}` : null,
        radius,
    ]);

    // Tick Timer
    useEffect(() => {
        const timer = setInterval(() => setMinuteTick((prev) => prev + 1), 30000);
        return () => clearInterval(timer);
    }, []);

    // Memoized Computations
    const allDepartures = useMemo(
        () => flattenDepartures(nearbyData, use24h, minuteTick),
        [nearbyData, use24h, minuteTick]
    );

    const activeAlerts = useMemo(() => getActiveAlerts(nearbyData), [nearbyData]);

    const displayItems = useMemo(
        () => getDisplayItemsFiltered(allDepartures, config),
        [allDepartures, config]
    );

    const groupedItems = useMemo(
        () =>
            config.displayMode === "grouped_by_route"
                ? groupDepartures(displayItems)
                : [],
        [displayItems, config.displayMode]
    );

    const gapStyle: React.CSSProperties =
        config.simpleListGap !== undefined
            ? { gap: `${parseFloat(config.simpleListGap) * 0.25}rem` }
            : { gap: "0.5rem" };

    const paddingStyle: React.CSSProperties =
        config.simplePaddingX !== undefined && config.simplePaddingY !== undefined
            ? {
                  padding: `${parseFloat(config.simplePaddingY) * 0.25}rem ${parseFloat(
                      config.simplePaddingX
                  ) * 0.25}rem`,
              }
            : config.useRouteColor
            ? { padding: "0.25rem 0.5rem" }
            : { padding: 0 };

    // Handlers
    const handleTripClick = (item: DisplayItem) => {
        if (!clickableTrips) return;
        if (item.tripId && item.chateau) {
            window.location.href = `/?mode=enroute&trip=${item.tripId}&chateau=${item.chateau}&24h=${use24h}&theme=${theme}`;
        }
    };

    const handleEdit = (e: React.MouseEvent) => {
        e.stopPropagation();
        onEdit?.();
    };

    return (
        <div
            className={`relative overflow-hidden rounded-lg border border-slate-600 flex flex-col ${className} ${
                theme === "default" ? "bg-slate-800/50" : ""
            }`}
            style={style}
        >
            {/* Header / Config Bar */}
            <div
                className={`flex items-center justify-between px-3 py-1 border-b border-slate-600 ${
                    isEditing ? "border-yellow-500/50" : ""
                } ${theme === "default" ? "bg-slate-900/80" : ""}`}
            >
                <span className="font-bold text-sm text-slate-300 truncate">
                    {config.name || (config.type === "departures" ? "Departures" : "Alerts")}
                </span>
                {isEditing && (
                    <button
                        onClick={handleEdit}
                        className="text-[10px] uppercase font-bold bg-yellow-600 text-black px-2 py-0.5 rounded ml-2 hover:bg-yellow-500"
                    >
                        Edit
                    </button>
                )}
            </div>

            {/* Content */}
            <div className="flex-grow overflow-auto p-2 scrollbar-hide">
                {loading && !nearbyData ? (
                    <div className="flex items-center justify-center h-full">
                        <span className="text-white/50 text-xs animate-pulse">Loading data...</span>
                    </div>
                ) : error ? (
                    <div className="flex items-center justify-center h-full p-4 text-center">
                        <span className="text-red-400 text-xs">{error}</span>
                    </div>
                ) : config.type === "departures" ? (
                    <div className="flex flex-col" style={gapStyle}>
                        {displayItems.length > 0 ? (
                            <>
                                {config.displayMode === "train_departure" ? (
                                    <div className="overflow-x-auto">
                                        <table className="w-full text-left font-mono text-sm border-spacing-0">
                                            <thead>
                                                <tr className="text-xs font-bold text-slate-400 border-b border-slate-700">
                                                    {config.showRouteShortName !== false && (
                                                        <th className="px-2 py-1">Rte</th>
                                                    )}
                                                    <th className="px-2 py-1">Time</th>
                                                    {config.showTripShortName !== false && (
                                                        <th className="px-2 py-1">Trip</th>
                                                    )}
                                                    <th className="px-2 py-1 w-full">Direction</th>
                                                    <th className="px-2 py-1 text-right">Plat</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {displayItems.map((item) => (
                                                    <tr
                                                        key={item.key}
                                                        className={`items-center ${
                                                            config.useRouteColor
                                                                ? "text-white font-bold"
                                                                : "border-b border-slate-700 last:border-0"
                                                        } ${
                                                            clickableTrips
                                                                ? "cursor-pointer hover:bg-white/10"
                                                                : ""
                                                        }`}
                                                        style={
                                                            config.useRouteColor
                                                                ? {
                                                                      backgroundColor: item.color,
                                                                      color: item.textColor,
                                                                  }
                                                                : {}
                                                        }
                                                        onClick={() => handleTripClick(item)}
                                                    >
                                                        {config.showRouteShortName !== false && (
                                                            <td className="px-2 py-1 font-bold">
                                                                {item.routeShortName}
                                                            </td>
                                                        )}
                                                        <td className="px-2 py-1 whitespace-nowrap">
                                                            {item.formattedTime}
                                                        </td>
                                                        {config.showTripShortName !== false && (
                                                            <td className="px-2 py-1 font-bold">
                                                                {item.tripShortName}
                                                            </td>
                                                        )}
                                                        <td className="px-2 py-1 truncate max-w-[100px]">
                                                            {item.headsign}
                                                        </td>
                                                        <td className="px-2 py-1 text-right">
                                                            {item.platform || "-"}
                                                        </td>
                                                    </tr>
                                                ))}
                                            </tbody>
                                        </table>
                                    </div>
                                ) : config.displayMode === "grouped_by_route" ? (
                                    <div className="flex flex-col gap-2">
                                        {groupedItems.map((group) => (
                                            <div
                                                key={group.routeShortName}
                                                className="flex rounded overflow-hidden border border-slate-600 bg-slate-800/50"
                                            >
                                                {/* Route Badge */}
                                                <div
                                                    className="w-12 flex items-center justify-center font-bold text-2xl shrink-0 p-2 border-r border-slate-700"
                                                    style={{
                                                        backgroundColor:
                                                            config.groupingTheme === "ratp"
                                                                ? group.routeColor
                                                                : "rgba(30, 41, 59, 0.5)",
                                                        color:
                                                            config.groupingTheme === "ratp"
                                                                ? group.routeTextColor
                                                                : group.routeColor,
                                                    }}
                                                >
                                                    {config.groupingTheme === "ratp" ? (
                                                        <div className="w-8 h-8 rounded-full border-2 border-current flex items-center justify-center">
                                                            {group.routeShortName.replace(" Line", "")}
                                                        </div>
                                                    ) : (
                                                        <span
                                                            className="text-white"
                                                            style={{ color: group.routeColor }}
                                                        >
                                                            {group.routeShortName.replace(" Line", "")}
                                                        </span>
                                                    )}
                                                </div>

                                                {/* Directions */}
                                                <div className="flex flex-col flex-grow text-xs">
                                                    {group.directions.map((direction, idx) => (
                                                        <div
                                                            key={direction.headsign}
                                                            className={`flex items-center justify-between p-2 gap-2 ${
                                                                idx < group.directions.length - 1
                                                                    ? "border-b border-slate-700"
                                                                    : ""
                                                            } ${idx % 2 === 0 ? "bg-white/5" : ""}`}
                                                        >
                                                            <div className="font-bold truncate text-sm flex-grow">
                                                                {direction.headsign}
                                                            </div>
                                                            <div className="flex items-center gap-2 shrink-0">
                                                                {direction.items.map((item) => (
                                                                    <div
                                                                        key={item.key}
                                                                        className={
                                                                            config.groupingTheme ===
                                                                            "ratp"
                                                                                ? "bg-black/40 rounded px-1.5 py-0.5 min-w-[3rem] text-center"
                                                                                : ""
                                                                        }
                                                                        onClick={(e) => {
                                                                            e.stopPropagation();
                                                                            handleTripClick(item);
                                                                        }}
                                                                        role="button"
                                                                        tabIndex={0}
                                                                        style={clickableTrips ? {cursor: "pointer", opacity: 0.8} : {}}

                                                                    >
                                                                        <span
                                                                            className={`font-bold text-lg leading-none ${
                                                                                config.groupingTheme ===
                                                                                "ratp"
                                                                                    ? "text-yellow-500"
                                                                                    : "text-white"
                                                                            }`}
                                                                        >
                                                                            {item.min}
                                                                        </span>
                                                                        <span className="text-[9px] opacity-70 ml-0.5 leading-none">
                                                                            min
                                                                        </span>
                                                                    </div>
                                                                ))}
                                                            </div>
                                                        </div>
                                                    ))}
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                ) : (
                                    /* Simple Mode */
                                    displayItems.map((item) => (
                                        <div
                                            key={item.key}
                                            className={`rounded leading-none flex items-center justify-between shadow hover:brightness-110 shrink-0 ${
                                                clickableTrips ? "cursor-pointer" : "cursor-default"
                                            }`}
                                            style={{
                                                ...(config.useRouteColor
                                                    ? {
                                                          backgroundColor: item.color,
                                                          color: item.textColor,
                                                      }
                                                    : {}),
                                                ...paddingStyle,
                                            }}
                                            onClick={() => handleTripClick(item)}
                                            role="button"
                                            tabIndex={0}
                                        >
                                            <div className="flex-grow overflow-hidden mr-2">
                                                <div className="flex items-baseline gap-1 overflow-hidden">
                                                    <span className="font-bold whitespace-nowrap">
                                                        {item.routeShortName}
                                                    </span>
                                                    <span className="font-medium truncate">
                                                        to {item.headsign}
                                                    </span>
                                                </div>
                                            </div>
                                            <div className="font-bold text-lg whitespace-nowrap">
                                                {item.min}
                                                <span className="text-xs font-light ml-0.5">min</span>
                                            </div>
                                        </div>
                                    ))
                                )}
                            </>
                        ) : (
                            <div className="text-white/50 text-center text-sm py-4">
                                No departures found.
                            </div>
                        )}
                    </div>
                ) : (
                    /* Alerts View */
                    <div className="flex flex-col gap-2">
                        {activeAlerts.length > 0 ? (
                            activeAlerts.map((alert, idx) => (
                                <div
                                    key={idx}
                                    className="bg-yellow-900/40 border border-yellow-700/50 p-2 rounded text-sm text-yellow-100"
                                >
                                    {alert}
                                </div>
                            ))
                        ) : (
                            <div className="text-white/50 text-center text-sm py-4">
                                No active alerts.
                            </div>
                        )}
                    </div>
                )}
            </div>

            {/* Overlay */}
            {isEditing && (
                <div
                    onClick={handleEdit}
                    className="absolute inset-0 bg-black/10 hover:bg-black/20 cursor-pointer transition-colors z-10 flex items-center justify-center opacity-0 hover:opacity-100"
                    role="button"
                    tabIndex={0}
                >
                    <span className="bg-black/80 text-white px-3 py-1 rounded-full text-xs font-bold pointer-events-none">
                        Configure Pane
                    </span>
                </div>
            )}
        </div>
    );
};
